name: ml_dart
description: A sample machine learning training run.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  ml_dataframe: ^0.5.1
  ml_preprocessing: ^6.0.0
  ml_algo: ^16.5.2
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
